#ifndef SERIALORDER_H
#define SERIALORDER_H

// Define the orders that can be sent and received
enum SerialOrder {
  HELLO = 0,
  RADAR_DISTANCE = 1,
  RADAR_POSITION = 2,
  ALREADY_CONNECTED = 3,
  SERIAL_ERROR = 4,
  RECEIVED = 5,
  MOTOR_SPEED = 6,
  STOP=7,
  MEASURED_ROLL = 8,
  MEASURED_PITCH = 9,
  MEASURED_YAW = 10,
  MEASURED_ACCEL_X = 110,
  MEASURED_ACCEL_Y = 120,
  MEASURED_ACCEL_Z = 130,
  REQUEST_ROLL = 18,
  REQUEST_PITCH = 19,
  REQUEST_YAW = 20,
  REQUEST_RADAR = 11,
  REQUEST_RADAR_POS = 12,
  PC_NOT_READY=111,
  STEER_COMMAND=13,
  REQUEST_STEER=23,
};

typedef enum SerialOrder SerialOrder;

#endif