#ifndef SERIALORDER_H
#define SERIALORDER_H

// Define the orders that can be sent and received
enum SerialOrder {
  HELLO = 0,
  RADAR_DISTANCE = 3,
  RADAR_POSITION = 2,
  //ALREADY_CONNECTED = 3,
  ARDUINO_READY = 4,
  PC_READY = 5,
  MOTOR_SPEED = 6,
  STOP=7,
  MEASURED_ROLL = 8,
  MEASURED_PITCH = 9,
  MEASURED_YAW = 10,
  MEASURED_ACCEL_X = 24,
  MEASURED_ACCEL_Y = 25,
  MEASURED_ACCEL_Z = 26,
  MEASURED_TIME = 31,
  REQUEST_ROLL = 18,
  REQUEST_PITCH = 19,
  REQUEST_YAW = 20,
  REQUEST_RADAR = 11,
  REQUEST_RADAR_POS = 12,
  PC_COMMS_EST = 111,
  ARD_COMMS_EST = 115,
  STEER_COMMAND = 13,
  REQUEST_COMMAND_MSB = 23,
  REQUEST_ACCEL_X = 34,
  REQUEST_ACCEL_Y = 35,
  REQUEST_ACCEL_Z = 36,
  BOARD_FOUND = 41,
  MOTOR_FWD_LEFT = 66,
  MOTOR_FWD_RIGHT = 67,
  MOTOR_REV_LEFT = 76,
  MOTOR_REV_RIGHT = 77,
  PC_HEARTBEAT = 55
};

typedef enum SerialOrder SerialOrder;

#endif